"use client";

import { useCallback, useEffect, useState } from "react";
import { AxiosError } from "axios";
import { Activity, ShieldCheck, UserCheck, UserX } from "lucide-react";
import { AuditLog, getAuditLogs, getTraceUsers, TraceUser, updateTraceUserStatus } from "@/lib/api";
import { ROLE_LABELS, useAuth } from "@/context/AuthContext";

export default function AdminPage(){
 const{user,token}=useAuth();const[users,setUsers]=useState<TraceUser[]>([]),[logs,setLogs]=useState<AuditLog[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState<string|number|null>(null);
 const load=useCallback(async()=>{if(!token||(user?.role!=="admin"&&user?.role!=="admin_hq"))return;try{const[u,a]=await Promise.all([getTraceUsers(token),getAuditLogs(token)]);setUsers(u);setLogs(a.items)}catch{setError("Không thể tải dữ liệu quản trị")}},[token,user?.role]);
 useEffect(()=>{void load()},[load]);
 if(user?.role!=="admin"&&user?.role!=="admin_hq")return <div className="rounded-2xl border border-red-500/30 bg-red-500/10 p-5 text-red-300">Bạn không có quyền truy cập khu vực quản trị.</div>;
 const update=async(target:TraceUser,approved:boolean,active:boolean)=>{setBusy(target.id);setError("");try{await updateTraceUserStatus(token,Number(target.id),{approved,active});await load()}catch(e:unknown){setError((e as AxiosError<{detail?:string}>)?.response?.data?.detail||"Không thể cập nhật tài khoản")}finally{setBusy(null)}};
 return <div className="mx-auto max-w-7xl space-y-6"><header><p className="text-sm font-bold text-emerald-400">QUẢN TRỊ HỆ THỐNG</p><h1 className="mt-1 text-3xl font-black text-white">Tài khoản và nhật ký bảo mật</h1></header>{error&&<p className="rounded-xl bg-red-500/10 p-3 text-red-300">{error}</p>}<section className="rounded-2xl border border-gray-800 bg-gray-900"><div className="border-b border-gray-800 p-5"><h2 className="flex items-center gap-2 font-bold text-white"><ShieldCheck className="text-emerald-400"/>Quản lý tài khoản</h2></div><div className="divide-y divide-gray-800">{users.map(x=><article key={x.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><strong className="text-white">{x.display_name}</strong><span className={`rounded-full px-2 py-0.5 text-xs ${x.approved&&x.active?"bg-emerald-500/15 text-emerald-300":"bg-amber-500/15 text-amber-300"}`}>{!x.approved?"Chờ duyệt":x.active?"Hoạt động":"Đã khóa"}</span></div><p className="mt-1 text-sm text-gray-400">@{x.username} · {x.organization} · {ROLE_LABELS[x.role]}</p></div>{x.id!==user.id&&<div className="flex gap-2">{!x.approved?<button disabled={busy===x.id} onClick={()=>void update(x,true,true)} className="flex min-h-10 items-center gap-2 rounded-xl bg-emerald-500 px-4 text-sm font-bold text-white"><UserCheck className="h-4 w-4"/>Phê duyệt</button>:<button disabled={busy===x.id} onClick={()=>void update(x,true,!x.active)} className="flex min-h-10 items-center gap-2 rounded-xl border border-gray-700 px-4 text-sm font-bold text-gray-300"><UserX className="h-4 w-4"/>{x.active?"Khóa":"Mở khóa"}</button>}</div>}</article>)}</div></section><section className="rounded-2xl border border-gray-800 bg-gray-900"><div className="border-b border-gray-800 p-5"><h2 className="flex items-center gap-2 font-bold text-white"><Activity className="text-blue-400"/>Audit log gần nhất</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="text-gray-500"><tr><th className="p-4">Thời gian</th><th>Hành động</th><th>Tài nguyên</th><th>IP</th><th>Người dùng</th></tr></thead><tbody>{logs.map(x=><tr key={x.id} className="border-t border-gray-800 text-gray-300"><td className="p-4">{new Date(x.created_at).toLocaleString("vi-VN")}</td><td className="font-mono text-xs text-emerald-300">{x.action}</td><td>{x.resource_type} {x.resource_id||""}</td><td>{x.ip_address||"—"}</td><td>{x.user_id||"Hệ thống"}</td></tr>)}</tbody></table></div></section></div>
}
