"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { Leaf, LockKeyhole } from "lucide-react";
import { useRouter, useSearchParams } from "next/navigation";
import { bootstrapTraceAdmin, getTraceAuthStatus, TraceRole } from "@/lib/api";
import { useAuth } from "@/context/AuthContext";

export default function AuthForm({mode}:{mode:"login"|"register"}){
 const router=useRouter(),params=useSearchParams(),auth=useAuth();const[busy,setBusy]=useState(false),[error,setError]=useState(""),[initialized,setInitialized]=useState<boolean|null>(null);
 const[form,setForm]=useState({username:"",password:"",display_name:"",organization:"",role:"producer" as Exclude<TraceRole,"admin">});
 useEffect(()=>{if(mode==="register")void getTraceAuthStatus().then(x=>setInitialized(x.initialized)).catch(()=>setInitialized(true))},[mode]);
 const submit=(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");const action=mode==="login"?auth.login(form.username,form.password):initialized===false?bootstrapTraceAdmin(form).then(x=>{localStorage.setItem("caymit_access_token",x.access_token);localStorage.setItem("trace_token",x.access_token)}):auth.register(form);void action.then(()=>{if(initialized===false)window.location.href="/";else if(mode==="register")router.replace("/login?registered=1");else router.replace(params.get("next")||"/")}).catch((e)=>setError(e?.response?.data?.detail||"Không thể xác thực. Vui lòng thử lại.")).finally(()=>setBusy(false))};
 const firstAdmin=mode==="register"&&initialized===false;
 return <main className="flex min-h-dvh items-center justify-center bg-gray-950 p-4"><div className="w-full max-w-md rounded-3xl border border-gray-800 bg-gray-900 p-6 shadow-2xl sm:p-8"><div className="mb-7 flex items-center gap-3"><div className="rounded-2xl bg-emerald-500 p-3"><Leaf className="h-6 w-6 text-white"/></div><div><h1 className="text-xl font-black text-white">CayMit AI</h1><p className="text-sm text-gray-500">Quản lý vườn mít thông minh</p></div></div><h2 className="text-2xl font-bold text-white">{mode==="login"?"Đăng nhập":firstAdmin?"Khởi tạo quản trị viên":"Tạo tài khoản"}</h2><p className="mt-1 text-sm text-gray-400">{mode==="login"?"Tiếp tục vào không gian vận hành của bạn.":firstAdmin?"Đây là tài khoản đầu tiên và sẽ quản trị toàn bộ hệ thống.":"Chọn đúng vai trò để hệ thống cấp quyền nghiệp vụ."}</p><form onSubmit={submit} className="mt-6 space-y-4">{mode==="register"&&<><Field label="Họ và tên" value={form.display_name} set={v=>setForm({...form,display_name:v})}/><Field label="Đơn vị / tổ chức" value={form.organization} set={v=>setForm({...form,organization:v})}/>{!firstAdmin&&<label className="block text-sm font-semibold text-gray-300">Vai trò<select value={form.role} onChange={e=>setForm({...form,role:e.target.value as Exclude<TraceRole,"admin">})} className="mt-2 min-h-12 w-full rounded-xl border border-gray-700 bg-gray-950 px-4 text-white"><option value="producer">Nông hộ / Hợp tác xã</option><option value="processor">Sơ chế / Đóng gói</option><option value="logistics">Logistics / Xuất khẩu</option></select></label>}</>}<Field label="Tên đăng nhập" value={form.username} set={v=>setForm({...form,username:v})}/><Field label="Mật khẩu (tối thiểu 8 ký tự)" type="password" value={form.password} set={v=>setForm({...form,password:v})}/>{error&&<p role="alert" className="rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-300">{error}</p>}<button disabled={busy||initialized===null&&mode==="register"} className="flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-emerald-500 font-bold text-white hover:bg-emerald-400 disabled:opacity-50"><LockKeyhole className="h-4 w-4"/>{busy?"Đang xử lý…":firstAdmin?"Khởi tạo hệ thống":mode==="login"?"Đăng nhập":"Đăng ký"}</button></form><p className="mt-6 text-center text-sm text-gray-400">{mode==="login"?"Chưa có tài khoản? ":"Đã có tài khoản? "}<Link className="font-bold text-emerald-400 hover:text-emerald-300" href={mode==="login"?"/register":"/login"}>{mode==="login"?"Đăng ký":"Đăng nhập"}</Link></p><Link href="/trace" className="mt-4 block text-center text-xs text-gray-500 hover:text-gray-300">Tra cứu QR không cần đăng nhập</Link></div></main>;
}
function Field({label,value,set,type="text"}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <label className="block text-sm font-semibold text-gray-300">{label}<input required minLength={type==="password"?8:3} type={type} value={value} onChange={e=>set(e.target.value)} className="mt-2 min-h-12 w-full rounded-xl border border-gray-700 bg-gray-950 px-4 text-white outline-none focus:border-emerald-400"/></label>}
